name: movies-platform

networks:
  edge:           # public-facing network (only nginx attaches here)
    name: movies_edge
    driver: bridge
  internal:       # private network for svc-to-svc and DB
    name: movies_internal
    driver: bridge
    internal: true

volumes:
  movies_db_data:
  users_db_data:

services:
  # --- Gateway ---
  gateway:
    image: ${GATEWAY_NGINX_IMAGE}
    container_name: gateway
    environment:
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      MOVIES_SERVICE_PORT: ${MOVIES_SERVICE_PORT}
    depends_on:
      movies-service:
        condition: service_started
      users-service:
        condition: service_started
    ports:
      - "${GATEWAY_SERVICE_PORT}:80"            # only exposed port
    volumes:
      - ./services/gateway/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./services/gateway/__docker-entrypoint.sh:/__docker-entrypoint.sh:ro
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - edge
      - internal

  # --- Microservices ---
  movies-service:
    build:
      context: ./services/movies
      dockerfile: Dockerfile
    container_name: movies_service
    depends_on:
      movies-db:
        condition: service_healthy
    #TODO: healthcheck:
    environment:
      SERVER_PORT: ${MOVIES_SERVICE_PORT}
      MOVIES_SERVICE_PORT: ${MOVIES_SERVICE_PORT}
      MOVIES_DB_URL: ${MOVIES_DB_URL}
      MOVIES_DB_USER: ${MOVIES_DB_USER}
      MOVIES_DB_PASSWORD: ${MOVIES_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      JWT_KEY: ${JWT_KEY}
    expose:
      - "${MOVIES_SERVICE_PORT}" # reachable only inside 'internal' and by gateway
    networks:
      internal:
        aliases:
          - movies-service

  users-service:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    container_name: users_service
    depends_on:
      users-db:
        condition: service_healthy
    #TODO: healthcheck:
    environment:
      SERVER_PORT: ${USERS_SERVICE_PORT}
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      USERS_DB_URL: ${USERS_DB_URL}
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PASSWORD: ${USERS_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
    expose:
      - "${USERS_SERVICE_PORT}" # reachable only inside 'internal' and by gateway
    networks:
      internal:
        aliases:
          - users-service

  # --- Databases ---
  movies-db:
    image: postgres:16
    container_name: ${MOVIES_DB_HOST}
    environment:
      POSTGRES_DB: ${MOVIES_DB_NAME}
      POSTGRES_USER: ${MOVIES_DB_USER}
      POSTGRES_PASSWORD: ${MOVIES_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - movies_db_data:/var/lib/postgresql/data
    networks:
      - internal

  users-db:
    image: postgres:16
    container_name: users_db
    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - users_db_data:/var/lib/postgresql/data
    networks:
      - internal
