receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Add resource processor to enrich data
  resource:
    attributes:
      - key: deployment.environment
        value: "docker"
        action: upsert

exporters:
  # Debug exporter for troubleshooting
  debug:
    verbosity: basic

  # OTLP exporter for traces to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: movies_platform
    const_labels:
      environment: docker

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]
