global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movies-service'
    static_configs:
      - targets: ['movies-service:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
