spring:
    application:
        name: users-service
    jpa:
      hibernate:
        ddl-auto: validate # Flyway will handle schema migrations
    flyway:
        enabled: true # Enable Flyway for database migrations
        locations: classpath:db/migration

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    endpoint:
        health:
            probes:
              enabled: true
server:
  port: 8764

logging:
  level:
    root: INFO
    io.github.gbessonov: INFO
    org.springframework.security: INFO
