spring:
  config:
    import: optional:file:../../.env.test[.properties]
    activate:
      on-profile: test

otel:
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: test
  service:
    name: movies-service
    namespace: movies-platform
