spring:
  config:
    import: optional:file:../../.env.test[.properties]
    activate:
      on-profile: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
      tags:
        application: movies-service
        environment: docker

otel:
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: test
  service:
    name: movies-service
    namespace: movies-platform
