spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: movies_user
    password: iddqd
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/movies
    user: movies_user
    password: iddqd
    locations: classpath:db/migration,classpath:db/migration/dev
jwt:
  key: 5b4e11d4-b718-4477-a61d-b3e7e83f3fe8
