spring:
    application:
        name: movies-service
    jpa:
      hibernate:
        ddl-auto: validate # Flyway will handle schema migrations
    flyway:
        enabled: true # Enable Flyway for database migrations
        locations: classpath:db/migration

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,ratelimiters
    endpoint:
        health:
            probes:
              enabled: true
server:
  port: 8765

logging:
  level:
    root: INFO
    io.github.gbessonov: INFO

resilience4j:
  ratelimiter:
    configs:
      instances:
        registerHealthIndicator: true
      default:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0s
        register-health-indicator: true
